name: 'thesis'
version: '1.0.0'
config-version: 2

profile: 'meltano'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: ../.meltano/transformers/dbt/target
clean-targets:
    - "../.meltano/transformers/dbt/target"
    - "dbt_modules"
    - "logs"

vars:
    'dbt_date:time_zone': 'Europe/Amsterdam'

models:
  thesis:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics